[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://mernbackend-tmp5.onrender.com/api"
  VITE_MOBILE_URL = "https://infinity-plaza.netlify.app"
  VITE_DESKTOP_URL = "https://shopping-canter.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200